# Generated by Django 4.2.1 on 2023-05-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_private',
            field=models.BooleanField(blank=True, null=True, verbose_name='Закрытый профиль'),
        ),
    ]
