# Generated by Django 4.2.1 on 2023-05-28 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
