# Generated by Django 4.2.1 on 2023-05-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_developer_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
    ]
