# Generated by Django 4.2.1 on 2023-05-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_product_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='build',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ImageField(help_text='Изображение должно быть в книжной ориентации (2:3)', upload_to='', verbose_name='Изображение'),
        ),
    ]
