# Generated by Django 4.2.1 on 2023-05-29 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_product_build_alter_product_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(blank=True, default=None, null=True, verbose_name='Принята заявка')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.developer', verbose_name='Компания')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_requestuser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
