# Generated by Django 4.2.1 on 2023-05-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_developerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Закрытый профиль'),
        ),
    ]
