# Generated by Django 4.2.1 on 2023-05-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_customuser_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
